## Arrays and DataFrame

#### 1. Arrays
##### As data scientists, we'll often be working with millions or even billions of numbers. For this, we need something faster than a list. Instead of lists, we will use arrays.

##### Arrays are provided by a package called NumPy . The package is called numpy, but it's standard to rename it np for brevity. You can do that with

In [1]:
import numpy as np
import numpy as np

#### Question 1.1 Use np.arange to create an array with the multiples of 99 from 0 up to (and including) 9999. (So its elements are 0, 99, 198, 297, etc.)

In [3]:
import numpy as np 
import pandas as pd 
a= np.arange(10000)*99
print(a)


[     0     99    198 ... 989703 989802 989901]


#### Question 1.2. Create an array of the time, in seconds, since the start of the month at which each hourly reading was taken. Name it collection_times.
##### Hint 1: There were 31 days in December, which is equivalent to (31×24 ) hours or (31×24×60×60) seconds. So your array should have 31×24 elements in it.

##### Hint 2: The len function works on arrays, too. check its length and make sure it has 31×24 elements.

In [5]:
import numpy as np 
import pandas as pd 
collection_times=np.arange(0,44640,60)
print (collection_times)

[    0    60   120   180   240   300   360   420   480   540   600   660
   720   780   840   900   960  1020  1080  1140  1200  1260  1320  1380
  1440  1500  1560  1620  1680  1740  1800  1860  1920  1980  2040  2100
  2160  2220  2280  2340  2400  2460  2520  2580  2640  2700  2760  2820
  2880  2940  3000  3060  3120  3180  3240  3300  3360  3420  3480  3540
  3600  3660  3720  3780  3840  3900  3960  4020  4080  4140  4200  4260
  4320  4380  4440  4500  4560  4620  4680  4740  4800  4860  4920  4980
  5040  5100  5160  5220  5280  5340  5400  5460  5520  5580  5640  5700
  5760  5820  5880  5940  6000  6060  6120  6180  6240  6300  6360  6420
  6480  6540  6600  6660  6720  6780  6840  6900  6960  7020  7080  7140
  7200  7260  7320  7380  7440  7500  7560  7620  7680  7740  7800  7860
  7920  7980  8040  8100  8160  8220  8280  8340  8400  8460  8520  8580
  8640  8700  8760  8820  8880  8940  9000  9060  9120  9180  9240  9300
  9360  9420  9480  9540  9600  9660  9720  9780  9

#### Question 1.3 The powers of 2 (20=1, 21=2, 22=4, etc) arise frequently in computer science. (For example, you may have noticed that storage on smartphones or USBs come in powers of 2, like 16 GB, 32 GB, or 64 GB.) Use np.arange and the exponentiation operator ** to compute the first 30 powers of 2, starting from 2^0.

##### Hint: Did your kernel "die" wen you ran your solution? There is a common incorrect response to this problem that tries to create

In [6]:
import numpy as np 
import pandas as pd 
power=2**np.arange(15)      # why not np.arange(15)**2
print(power)


[    1     2     4     8    16    32    64   128   256   512  1024  2048
  4096  8192 16384]


#### Question 1.4 Get all items between 5 and 10 from a.

##### Input:

###### a = np.array([2, 6, 1, 9, 10, 3, 27])
 
#### Desired Output:

##### (array([6, 9, 10]),)

In [7]:
a=np.array([2,6,1,9,10,3,27])
a[1:4:2]  

array([6, 9])

#### Question 1.5 Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

##### Input:

##### a = np.array([1,2,3])`

##### Desired Output:

##### array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

##### Hint:You may use numpy repeat,tile

In [8]:

import numpy as np 
import pandas as pd
a=np.array([1,2,3])
np.a=[np.repeat(a,3), np.tile(a,3)]
print(np.a)

[array([1, 1, 1, 2, 2, 2, 3, 3, 3]), array([1, 2, 3, 1, 2, 3, 1, 2, 3])]
